---
- name: Install Java 1.7
  ansible.builtin.yum:

- name: add group "tomcat"
  ansible.builtin.group:

- name: add user "tomcat"
  become: true
  become_method: sudo
  ansible.builtin.user:

- name: Download Tomcat
  ansible.builtin.get_url:

- name: Extract archive
  ansible.builtin.command:

- name: Symlink install directory
  ansible.builtin.file:

- name: Change ownership of Tomcat installation
  ansible.builtin.file:

- name: Configure Tomcat server
  notify: restart tomcat
  ansible.builtin.template:

- name: Configure Tomcat users
  notify: restart tomcat
  ansible.builtin.template:

- name: Install Tomcat init script
  ansible.builtin.copy:

- name: Start Tomcat
  ansible.builtin.service:

- name: deploy iptables rules
  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version == '6'
  notify: restart iptables
  ansible.builtin.template:

- name: insert firewalld rule for tomcat http port
  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7'
  ansible.posix.firewalld:

- name: insert firewalld rule for tomcat https port
  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7'
  ansible.posix.firewalld:

- name: wait for tomcat to start
  ansible.builtin.wait_for:
