---
- name: test raw module
  hosts: all
  tasks:
    - name: run ipconfig

- name: test stat module
  hosts: windows
  tasks:
    - name: test stat module on file
      register: stat_file
      ansible.windows.win_stat:


    - name: check stat_file result
      ansible.builtin.assert:
        that:
          - stat_file.stat.exists
          - not stat_file.stat.isdir
          - stat_file.stat.size > 0
          - stat_file.stat.md5
