---
# This playbook does a rolling update for all webservers serially (one at a time).
# Change the value of serial: to adjust the number of server to be updated.
#
# The three roles that apply to the webserver hosts will be applied: common,
# base-apache, and web. So any changes to configuration, package updates, etc,
# will be applied as part of the rolling update process.
#

# gather facts from monitoring nodes for iptables rules
- hosts: monitoring
  tasks: []

- hosts: webservers
  serial: 1

  # These are the tasks to run before applying updates:
  pre_tasks:
    - name: disable nagios alerts for this host webserver service
      delegate_to: "{{ item }}"
      with_items: "{{ groups.monitoring }}"
      community.general.nagios:

    - name: disable the server in haproxy
      haproxy: state=disabled backend=myapplb host={{ inventory_hostname }} socket=/var/lib/haproxy/stats
      delegate_to: "{{ item }}"
      with_items: "{{ groups.lbservers }}"

    - common
    - base-apache
    - web

  # These tasks run after the roles:
  post_tasks:
    - name: wait for webserver to come up
      ansible.builtin.wait_for:

    - name: enable the server in haproxy
      delegate_to: "{{ item }}"
      with_items: "{{ groups.lbservers }}"
      community.general.haproxy:

    - name: re-enable nagios alerts
      delegate_to: "{{ item }}"
      with_items: "{{ groups.monitoring }}"
      community.general.nagios:
