---
- hosts: all
  serial: 3

  # now each of the tasks below will complete on 3 hosts before moving on to the next 3, regardless of how many
  # hosts are selected by the "hosts:" line

  tasks:
    - name: ping

    - name: ping2
      ansible.builtin.ping:
