---
# this is a demo of conditional executions using 'when' statements, which can skip
# certain tasks on machines/platforms/etc where they do not apply.

- hosts: all
  remote_user: root

  vars:
    favcolor: red
    dog: fido
    cat: whiskers
    ssn: 8675309

  tasks:
    - name: do this if my favcolor is blue, and my dog is named fido
      when: favcolor == 'blue' and dog == 'fido'
      ansible.builtin.shell: /bin/false

    - name: do this if my favcolor is not blue, and my dog is named fido
      when: favcolor != 'blue' and dog == 'fido'
      ansible.builtin.shell: /bin/true

    - name: do this if my SSN is over 9000
      when: ssn > 9000
      ansible.builtin.shell: /bin/true

    - name: do this if I have one of these SSNs
      when: ssn in [ 8675309, 8675310, 8675311 ]
      ansible.builtin.shell: /bin/true

    - name: do this if a variable named hippo is NOT defined
      when: hippo is not defined
      ansible.builtin.shell: /bin/true

    - name: do this if a variable named hippo is defined
      when: hippo is defined

      ansible.builtin.shell: /bin/true
