---
- hosts: webservers
  vars:
    - jquery_directory: /var/www/html/javascript
    - person: Susie%20Smith
  tasks:
    - name: Create directory for jQuery

    - name: Grab a bunch of jQuery stuff
      with_items:
        - jquery.min.js
        - mobile/latest/jquery.mobile.min.js
        - ui/jquery-ui-git.css
      ansible.builtin.get_url:
      url: http://code.jquery.com/{{item}}
      dest: "{{jquery_directory}}"
