---
# This is a demo of how the group command works.

- hosts: all
  remote_user: root
  become: true
  become_method: sudo

  tasks:
    # Walk through group creation, modification, and deletion

    - name: create a group
      ansible.builtin.group:
