---
# this is an example of how to run repeated task elements over lists
# of items, for example, installing multiple packages or configuring
# multiple users

- hosts: all
  remote_user: root

  tasks:
    - name: install packages
      ansible.builtin.yum:
        name:
          - cobbler
          - httpd

    - name: configure users
      ansible.builtin.user:
        name: "{{ item }}"
        state: present

    - name: remove users
      with_items:
        - testuser1
        - testuser2
      ansible.builtin.user:

    - name: copy templates
      with_items:
        - src: templates/testsource1
          dest: /example/dest1/test.conf
        - src: templates/testsource2
          dest: /example/dest2/test.conf
      ansible.builtin.template:
