---
# this is a trivial example of how to do a nested loop.

- hosts: all
  tasks:
    - shell: echo "nested test a={{ item[0] }} b={{ item[1] }} c={{ item[2] }}"

# you can reference a raw variable name without putting it in {{ brackets }}

- hosts: all
  vars:
    listvar1:
    - 'a'
    - 'b'
    - 'c'
  tasks:
    - shell: echo "nested test a={{ item[0] }} b={{ item[1] }}"
