---
- hosts: all
  remote_user: root

  tasks:
    - name: Create database user
      community.mysql.mysql_user:

    - name: Create database
      community.mysql.mysql_db:

    - name: Ensure no user named 'sally' exists and delete if found.
      community.mysql.mysql_user:
