---
- hosts: webservers
  become: true
  gather_facts: false

  tasks:
    - name: ensure apt cache is up to date

    - name: ensure packages are installed
      ansible.builtin.apt:
        name:
          - postgresql
          - libpq-dev
          - python-psycopg2

- hosts: webservers
  become: true
  become_user: postgres
  gather_facts: false

  vars:
    dbname: myapp
    dbuser: django
    dbpassword: mysupersecretpassword

  tasks:
    - name: ensure database is created
      community.postgresql.postgresql_db:

    - name: ensure user has access to database
      community.postgresql.postgresql_user:

    - name: ensure user does not have unnecessary privilege
      community.postgresql.postgresql_user:

    - name: ensure no other user can access the database
      community.postgresql.postgresql_privs:
