---
- hosts: rabbitmq
  become: true
  become_method: sudo
  vars:
    rabbitmq_version: 3.0.2-1

  tasks:
    - name: ensure python-software-properties is installed
      ansible.builtin.apt:

    - name: add rabbitmq official apt repository
      ansible.builtin.apt_repository:

    - name: add trusted key
      ansible.builtin.apt_key:

    - name: install package
      ansible.builtin.apt:
        name:

    - name: enable rabbitmq plugins
      notify:
        - restart rabbitmq
      community.rabbitmq.rabbitmq_plugin:

    - name: add users
      with_items:

    - name: remove default guest user
      community.rabbitmq.rabbitmq_user:

    - name: ensure vhost /test is present
      rabbitmq_vhost: name=/test state=present

    - name: restart rabbitmq
      ansible.builtin.service:
