---
# this is an example of how to template a file over using some variables derived
# from the system.  For instance, if you wanted to have different configuration
# templates by OS version, this is a neat way to do it.  Any Ansible facts, facter facts,
# or ohai facts could be used to do this.

- hosts: all

  tasks:
    - name: template a config file
      first_available_file:
        # first see if we have a file for this specific host
        - /srv/whatever/{{ansible_hostname}}.conf
        - /srv/whatever/{{ansible_distribution}}{{ansible_distribution_version}}.conf
        - /srv/whatever/{{ansible_distribution}}.conf
        - /srv/whatever/default
      ansible.builtin.template:
        dest: /etc/imaginary_file.conf
