---
# this is a demo of how the user commands work and how to reference salted passwords
# in vars sections.  You could also use vars_files if you like (see other examples)

- hosts: all
  remote_user: root
  vars:
    # created with:
    # python -c 'import crypt; print crypt.crypt("This is my Password", "$1$SomeSalt$")'
    password: $1$SomeSalt$UqddPX3r4kH3UL5jq5/ZI.

  tasks:
    # Walk through account creation, modification, and deletion

    - name: test basic user account creation
      ansible.builtin.user:

    # the following is just a simple example of how you don't have to include
    # the 'name' element for each task
