---
##
# Example Ansible playbook that uses the Zfs module.
#

- hosts: webservers
  gather_facts: false
  become: true
  become_method: sudo

  vars:
    pool: rpool

  tasks:
    - name: Create a zfs file system
      community.general.zfs:

    - name: Create a zfs file system with quota of 10GiB and visible snapdir
      community.general.zfs:

    - name: Create zfs snapshot of the above file system
      community.general.zfs:

    - name: Create zfs volume named smallvol with a size of 10MiB
      community.general.zfs:

    - name: Removes snapshot of rpool/oldfs
      community.general.zfs:

    - name: Removes file system rpool/oldfs
      community.general.zfs:
