---
- name: Install libselinux-python
  ansible.builtin.yum:

- name: Install GPG key for EPEL
  ansible.builtin.get_url:

- name: Install EPEL repository
  ansible.builtin.yum:

- name: Setup Iptables rules
  notify: restart iptables
  ansible.builtin.template:
