---
# Handler to handle DB tier notifications
- name: restart mysql
  ansible.builtin.service:
    name: mysqld
    state: restarted

- name: restart iptables
  ansible.builtin.service:
    name: iptables
    state: restarted
