---
# This playbook will install MariaDB and create db user and give permissions.
- name: Install MariaDB package
  ansible.builtin.yum:
    name:
      - mariadb-server
      - MySQL-python
      - libselinux-python
      - libsemanage-python

- name: Configure SELinux to start mysql on any port
  ansible.posix.seboolean:

- name: Create Mysql configuration file
  notify:
    - restart mariadb
  ansible.builtin.template:

- name: Create MariaDB log file
  ansible.builtin.file:

- name: Start MariaDB Service
  ansible.builtin.service:

- name: insert firewalld rule
  ignore_errors: true
  ansible.posix.firewalld:
