---
- name: Install php-fpm and deps
  ansible.builtin.yum:
    name:
      - php
      - php-fpm
      - php-enchant
      - php-IDNA_Convert
      - php-mbstring
      - php-mysql
      - php-PHPMailer
      - php-process
      - php-simplepie
      - php-xml

- name: Disable default pool
  notify: restart php-fpm
  ansible.builtin.command: mv /etc/php-fpm.d/www.conf /etc/php-fpm.d/www.disabled creates=/etc/php-fpm.d/www.disabled

- name: Copy php-fpm configuration
  notify: restart php-fpm
  ansible.builtin.template:
