---
# This Playbook runs all the common plays in the deployment
- name: Create the hosts file for all machines
  ansible.builtin.template:

- name: Create the repository for 10Gen
  ansible.builtin.copy:

- name: Create the EPEL Repository.
  ansible.builtin.copy:

- name: Create the GPG key for EPEL
  ansible.builtin.copy:

- name: Create the mongod user
  ansible.builtin.user:

- name: Create the data directory for the namenode metadata
  ansible.builtin.file:

- name: Install the mongodb package
  ansible.builtin.yum:
    name:
      - libselinux-python
      - mongo-10gen
      - mongo-10gen-server
      - bc
      - python-pip

- name: Install the latest pymongo package
  ansible.builtin.pip:

- name: Create the iptables file
  notify: restart iptables
  ansible.builtin.template:
