---
- name: Download WordPress
  ansible.builtin.get_url:

- name: Extract archive
  ansible.builtin.unarchive:
    creates: /srv/wordpress
    src: /srv/wordpress-{{ wp_version }}.tar.gz
    dest: /srv/wordpress

- name: Add group "wordpress"
  ansible.builtin.group:

- name: Add user "wordpress"
  ansible.builtin.user:

- name: Fetch random salts for WordPress config
  register: wp_salt
  become: false
  become_method: sudo
  changed_when: true
  delegate_to: localhost
  ansible.builtin.get_url:
    url: https://api.wordpress.org/secret-key/1.1/salt/

- name: Create WordPress database
  community.mysql.mysql_db:

- name: Create WordPress database user
  community.mysql.mysql_user:

- name: Copy WordPress config file
  ansible.builtin.template:

- name: Change ownership of WordPress installation
  ansible.builtin.file:

- name: Start php-fpm Service
  ansible.builtin.service:
