---
# This role deploys the mongod processes and sets up the replication set.
- name: create data directory for mongodb
  delegate_to: "{{ item }}"
  with_items: groups.replication_servers
  ansible.builtin.file:

- name: create log directory for mongodb
  ansible.builtin.file:

- name: create run directory for mongodb
  ansible.builtin.file:

- name: Create the mongodb startup file
  delegate_to: "{{ item }}"
  with_items: groups.replication_servers

  ansible.builtin.template:

- name: Create the mongodb configuration file
  delegate_to: "{{ item }}"
  with_items: groups.replication_servers
  ansible.builtin.template:

- name: Copy the keyfile for authentication
  ansible.builtin.copy:

- name: Start the mongodb service
  delegate_to: "{{ item }}"
  with_items: groups.replication_servers
  ansible.builtin.command:

- name: Create the file to initialize the mongod replica set
  ansible.builtin.template:

- name: Pause for a while
  ansible.builtin.pause:

- name: Initialize the replication set
  ansible.builtin.shell: /usr/bin/mongo --port "{{ mongod_port }}" /tmp/repset_init.js
