---
#This Playbooks adds shards to the mongos servers once everythig is added
- name: Create the file to initialize the mongod Shard
  delegate_to: "{{ item }}"
  with_items: groups.mongos_servers
  ansible.builtin.template:

- name: Add the shard to the mongos
  delegate_to: "{{ item }}"
  with_items: groups.mongos_servers

  ansible.builtin.shell: /usr/bin/mongo localhost:{{ mongos_port }}/admin -u admin -p {{ mongo_admin_pass }} /tmp/shard_init_{{ inventory_hostname }}.js
