---
- hosts: localhost
  gather_facts: false
  connection: local
  vars:
    ansible_mango:
      true: true
      bri: 254
      xy: [!!float "0.5701", !!float "0.313"]
    ansible_pool:
      true: true
      bri: 254
      xy: [!!float "0.1593", !!float "0.2522"]
  tasks:
    - name: INCLUDE UNIQUE USERNAME FROM REGISTER.YML
      ansible.builtin.include_vars:
        file: username_info.yml

    - name: GRAB HUE LIGHT INFORMATION
      register: light_info
      ansible.builtin.uri:
        url: http://{{ip_address}}/api/{{username}}
        method: GET
        body: "{{body_info|to_json}}"

    - name: TURN LIGHTS TO MANGO
      loop: "{{ range(1, light_info.json.lights | length + 1)|list }}"
      ansible.builtin.uri:
        url: http://{{ip_address}}/api/{{username}}/lights/{{item}}/state
        method: PUT
        body: "{{ansible_mango|to_json}}"

    - name: TURN LIGHTS TO POOL
      loop: "{{ range(1, light_info.json.lights | length + 1)|list }}"
      ansible.builtin.uri:
        url: http://{{ip_address}}/api/{{username}}/lights/{{item}}/state
        method: PUT
        body: "{{ansible_pool|to_json}}"

    - name: TURN LIGHTS TO MANGO
      loop: "{{ range(1, light_info.json.lights | length + 1)|list }}"
      ansible.builtin.uri:
        url: http://{{ip_address}}/api/{{username}}/lights/{{item}}/state
        method: PUT
        body: "{{ansible_mango|to_json}}"

    - name: TURN LIGHTS TO POOL
      loop: "{{ range(1, light_info.json.lights | length + 1)|list }}"
      ansible.builtin.uri:
        url: http://{{ip_address}}/api/{{username}}/lights/{{item}}/state
        method: PUT
        body: "{{ansible_pool|to_json}}"
