---
- hosts: localhost
  gather_facts: false
  connection: local

  vars:
    off_state:
      true: false
    on_state:
      true: true

  tasks:
    - name: INCLUDE UNIQUE USERNAME FROM REGISTER.YML
      ansible.builtin.include_vars:
        file: username_info.yml

    - name: GRAB HUE LIGHT INFORMATION
      register: light_info
      ansible.builtin.uri:
        url: http://{{ip_address}}/api/{{username}}
        method: GET
        body: "{{body_info|to_json}}"

    - name: PRINT DATA TO TERMINAL WINDOW
      ansible.builtin.debug:
        var: light_info.json.lights

    - name: PRINT AMOUNT OF LIGHTS TO TERMINAL WINDOW
      ansible.builtin.debug:
        msg: THERE ARE {{light_info.json.lights | length}} HUE LIGHTS PRESENT

    # - name: PRINT OUT LOOP VARS
    #   debug:
    #     msg: "http://{{ip_address}}/api/{{username}}/lights/{{item}}/state"
    #   loop: "{{ range(1, light_info.json.lights | length + 1)|list }}"

    - name: TURN LIGHTS OFF
      loop: "{{ range(1, light_info.json.lights | length + 1)|list }}"
      ansible.builtin.uri:
        url: http://{{ip_address}}/api/{{username}}/lights/{{item}}/state
        method: PUT
        body: "{{off_state|to_json}}"

    - name: PROMPT USER TO TURN BACK ON
      ansible.builtin.pause:
        prompt: Turn them back on?

    - name: TURN LIGHTS ON
      loop: "{{ range(1, light_info.json.lights | length + 1)|list }}"
      ansible.builtin.uri:
        url: http://{{ip_address}}/api/{{username}}/lights/{{item}}/state
        method: PUT
        body: "{{on_state|to_json}}"
