---
- hosts: localhost
  gather_facts: false
  connection: local

  tasks:
    - name: PROMPT USER TO PRESS PHYSICAL BUTTON HUE HUB
      ansible.builtin.pause:
        prompt: Press the button on the hub now...

    - name: INCLUDE IP ADDRESS FROM username_info.yml
      ansible.builtin.include_vars:
        file: username_info.yml

    - name: GRAB UNIQUE USERNAME
      register: username_info
      ansible.builtin.uri:
        url: http://{{ip_address}}/api
        method: POST
        body: "{{body_info|to_json}}"

    - name: PRINT DATA TO TERMINAL WINDOW
      ansible.builtin.debug:

        path: ./username_info.yml
        regexp: ^username
        insertafter: EOF
        line: 'username: {{username_info.json[0]["success"]["username"]}}'
