---
#Provision some instances:
- hosts: localhost
  connection: local
  gather_facts: false

  vars_files:
    - group_vars/all

  tasks:
    - name: Launch webserver instances
      ec2: >
        access_key="{{ ec2_access_key }}"
        secret_key="{{ ec2_secret_key }}"
        keypair="{{ ec2_keypair }}"
        group="{{ ec2_security_group }}"
        type="{{ ec2_instance_type }}"
        image="ami-0d789266"
        region="{{ ec2_region }}"
        instance_tags="{'ansible_group':'windows_webservers', 'type':'{{ ec2_instance_type
        }}', 'group':'{{ ec2_security_group }}', 'Name':'demo_''{{ tower_user_name }}'}"
        count="{{ ec2_instance_count }}"
        wait=true
      register: ec2

      tags:
        - web

    - name: Launch database instance
      ec2: >
        access_key="{{ ec2_access_key }}"
        secret_key="{{ ec2_secret_key }}"
        keypair="{{ ec2_keypair }}"
        group="{{ ec2_security_group }}"
        type="{{ ec2_instance_type }}"
        image="ami-17d66f7c"
        region="{{ ec2_region }}"
        instance_tags="{'ansible_group':'windows_dbservers', 'type':'{{ ec2_instance_type
        }}', 'group':'{{ ec2_security_group }}', 'Name':'demo_''{{ tower_user_name }}'}"
        count="1"
        wait=true
      register: ec2

      tags:
        - db

    - name: Wait for WinRM to come up
      local_action:
        module: ansible.builtin.wait_for
        host: "{{ item.public_dns_name }}"
      with_items: ec2.instances
