---
# This playbook contains common plays that will be run on all nodes.
- name: Install ntp
  tags: ntp
  ansible.builtin.yum:
    name: ntp
    state: present

- name: Configure ntp file
  tags: ntp
  notify: restart ntp
  ansible.builtin.template:
    src: ntp.conf.j2
    dest: /etc/ntp.conf

- name: Start the ntp service
  tags: ntp
  ansible.builtin.service:
    name: ntpd
    state: started
    enabled: true

- name: test to see if selinux is running
  register: sestatus
  changed_when: false
  ansible.builtin.command: getenforce
